apiVersion: apps/v1
kind: Deployment
metadata:
  name: boom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boom
  template:
    metadata:
      labels:
        app: boom
    spec:
      containers:
        - name: boom
          image: registry.cn-hangzhou.aliyuncs.com/mse-ingress/boom
          imagePullPolicy: Always
      imagePullSecrets:
        - name: demo-secret